# Generated by Django 5.0.3 on 2024-04-24 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
