# Generated by Django 5.0.3 on 2024-04-25 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
    ]
