# Generated by Django 5.0.3 on 2024-04-28 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0012_comment_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
    ]
